require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  test-prof: config/rubocop-rspec.yml

AllCops:
  NewCops: disable
  Exclude:
    - Aptfile
    - Brewfile
    - Gemfile
    - Guardfile
    - Rakefile
    - config.ru
    - '.**'
    - '**/*.md'
    - '**/**.yml'
    - app/assets/**/*
    - benches/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - docs/**/*
    - hidden/**/*
    - lib/**/*
    - log/**/*
    - node_modules/**/*
    - pkg/**/*
    - public/**/*
    - storage/**/*
    - test/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - spec/support/**/**
    - tmp/**/*
    - vendor/**/*
  TargetRubyVersion: 2.7
  UseCache: true
Layout/LineLength:
  AllowURI: true
  Enabled: false
  Max: 120
Naming/MemoizedInstanceVariableName:
  Enabled: false
Metrics/AbcSize:
  Max: 42
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/MethodLength:
  CountComments: false
  Max: 43
Metrics/ModuleLength:
  Max: 164
Metrics/PerceivedComplexity:
  Max: 14
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/HashEachMethods:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false

##############################
# Rails specific
##############################
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/InverseOf:
  Enabled: false
